stages:
  preprocess_tabular:
    cmd: python -m src.data_prep
    deps:
      - Data/Wildfire_Dataset.csv
      - src/data_prep.py
      - src/config.py
    outs:
      - Data/processed

  create_sequences:
    cmd: python -m src.data_prep_seq
    deps:
      - Data/processed
      - src/data_prep_seq.py
      - src/config.py
    outs:
      - Data/processed_seq

  train:
    cmd: python train.py
    deps:
      - Data/processed_seq
      - train.py
      - src/trainer.py
      - src/models
      - src/config.py
    outs:
      - models
