apiVersion: v1
kind: Service
metadata:
  name: wildfire-service
  namespace: wildfire
spec:
  type: NodePort
  selector:
    app: wildfire-inference
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
